version: "3.8"

services:
  transmission:
    build: ./transmission
    volumes:
      - ${TORRENT_DOWNLOAD_DIR}/:/downloads
    ports:
      - "51413:51413"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
        reservations:
          cpus: "0.25"
          memory: 20M
  web:
    build: ./web
    env_file:
      - nginx.env
    volumes:
      - ${TORRENT_DOWNLOAD_DIR}/:/var/Downloads
      - ${NGINX_WEB_DIR}/:/var/www
      - ${NGINX_WEB_SSL}/:/etc/nginx/ssl
      - ${NGINX_WEB_RESTRICT}/:/etc/nginx/restrict
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - transmission
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
        reservations:
          cpus: "0.25"
          memory: 20M
